FROM maven:3-openjdk-11 as build-stage
WORKDIR /app
COPY . /app
RUN mvn -B package -P-build-frontend


FROM tomcat:9-jdk11-openjdk

ENV TZ='Europe/Rome'

RUN mkdir -p $CATALINA_HOME/webapps/ROOT/WEB-INF/
WORKDIR $CATALINA_HOME/webapps/ROOT

ADD 'https://jdbc.postgresql.org/download/postgresql-42.2.12.jar' $CATALINA_HOME/lib/

COPY --from=build-stage /app/target/demo-1.0.war $CATALINA_HOME/webapps/ROOT.war

RUN jar xf ../ROOT.war; rm -f ../ROOT.war
